export const inventory = [
  {
    id: 1,
    brand: "Mercedes-Benz",
    model: "AMG GT R",
    year: 2021,
    mileage: "12,500 mi",
    engine: "V8 BiTurbo",
    price: "$145,000",
    image: "/images/car1.jpg",
    description: "The Mercedes-AMG GT R is a track-focused beast that delivers uncompromising performance and breathtaking design. Featuring advanced aerodynamics and a handcrafted V8 biturbo engine.",
    horsepower: "577 hp",
    transmission: "7-Speed Dual-Clutch",
    features: ["Carbon Fiber Roof", "Burmester Surround Sound", "AMG Performance Seats", "Rear-Wheel Steering"]
  },
  {
    id: 2,
    brand: "Audi",
    model: "R8 V10 Performance",
    year: 2022,
    mileage: "8,200 mi",
    engine: "5.2L V10",
    price: "$168,500",
    image: "/images/car2.jpg",
    description: "Experience the pinnacle of Audi engineering with the R8 V10 Performance. A naturally aspirated powerhouse paired with the legendary quattro all-wheel-drive system.",
    horsepower: "602 hp",
    transmission: "7-Speed S tronic",
    features: ["Carbon Ceramic Brakes", "Laser Headlights", "Bang & Olufsen Audio", "Sport Exhaust"]
  },
  {
    id: 3,
    brand: "BMW",
    model: "M8 Competition",
    year: 2023,
    mileage: "5,000 mi",
    engine: "4.4L V8",
    price: "$135,000",
    image: "/images/car3.jpg",
    description: "The BMW M8 Competition blends supreme grand touring comfort with supercar acceleration. A masterpiece of luxury and driving dynamics.",
    horsepower: "617 hp",
    transmission: "8-Speed M Steptronic",
    features: ["M xDrive", "Bowers & Wilkins Diamond Surround", "Merino Leather", "Carbon Core"]
  },
  {
    id: 4,
    brand: "Mercedes-Benz",
    model: "S-Class 580",
    year: 2022,
    mileage: "15,300 mi",
    engine: "4.0L V8",
    price: "$112,000",
    image: "/images/car4.jpg",
    description: "The benchmark for luxury sedans. The S580 offers an unmatched ride quality, state-of-the-art technology, and an incredibly quiet, opulent cabin.",
    horsepower: "496 hp",
    transmission: "9-Speed Automatic",
    features: ["MBUX Infotainment", "Massaging Seats", "Augmented Reality HUD", "Air Suspension"]
  },
  {
    id: 5,
    brand: "BMW",
    model: "X5 M50i",
    year: 2021,
    mileage: "22,000 mi",
    engine: "4.4L V8",
    price: "$78,500",
    image: "/images/car5.jpg",
    description: "The X5 M50i combines the versatility of a premium SUV with the heart-pounding performance of a sports car.",
    horsepower: "523 hp",
    transmission: "8-Speed Sport Automatic",
    features: ["xDrive All-Wheel Drive", "Adaptive M Suspension", "Panoramic Sky Lounge", "Harman Kardon Audio"]
  },
  {
    id: 6,
    brand: "Audi",
    model: "RS7 Sportback",
    year: 2023,
    mileage: "4,100 mi",
    engine: "4.0L V8",
    price: "$125,000",
    image: "/images/car6.jpg",
    description: "Striking design meets raw power. The RS7 Sportback is a versatile daily driver that can dominate the autobahn with ease.",
    horsepower: "591 hp",
    transmission: "8-Speed Tiptronic",
    features: ["quattro Sport Rear Differential", "RS Adaptive Air Suspension", "Valcona Leather", "HD Matrix-Design Headlights"]
  },
  {
    id: 7,
    brand: "Porsche",
    model: "911 GT3",
    year: 2022,
    mileage: "2,800 mi",
    engine: "4.0L Flat-6",
    price: "$210,000",
    image: "/images/car7.jpg",
    description: "The quintessential driver's car. The 911 GT3 offers telepathic steering, a screaming naturally aspirated engine, and track-ready performance.",
    horsepower: "502 hp",
    transmission: "7-Speed PDK",
    features: ["Carbon Fiber Bucket Seats", "Rear-Axle Steering", "Front Axle Lift", "Sport Exhaust System"]
  },
  {
    id: 8,
    brand: "BMW",
    model: "M4 Competition",
    year: 2023,
    mileage: "6,500 mi",
    engine: "3.0L Twin-Turbo I6",
    price: "$85,000",
    image: "/images/car8.jpg",
    description: "Aggressive styling meets explosive power. The M4 Competition is a versatile coupe that dominates both the daily commute and weekend track days.",
    horsepower: "503 hp",
    transmission: "8-Speed M Steptronic",
    features: ["M Carbon Exterior Package", "Harman Kardon Audio", "Laserlight Headlights", "Merino Leather"]
  },
  {
    id: 9,
    brand: "McLaren",
    model: "720S",
    year: 2021,
    mileage: "4,200 mi",
    engine: "4.0L Twin-Turbo V8",
    price: "$275,000",
    image: "/images/car9.jpg",
    description: "A true supercar experience. The McLaren 720S bends the laws of physics with its featherlight carbon fiber chassis and blistering acceleration.",
    horsepower: "710 hp",
    transmission: "7-Speed SSG",
    features: ["Proactive Chassis Control II", "Bowers & Wilkins Audio", "Carbon Fiber Monocage II", "Dihedral Doors"]
  },
  {
    id: 10,
    brand: "Mercedes-Benz",
    model: "G-Class G63 AMG",
    year: 2022,
    mileage: "11,000 mi",
    engine: "4.0L V8 BiTurbo",
    price: "$195,000",
    image: "/images/car10.jpg",
    description: "The ultimate status symbol. The G63 AMG combines military-grade off-road capability with extreme luxury and an unmistakable road presence.",
    horsepower: "577 hp",
    transmission: "9-Speed AMG SPEEDSHIFT",
    features: ["Burmester Surround Sound", "Exclusive Nappa Leather", "AMG Night Package", "Three Differential Locks"]
  }
];
